
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 4 */2 * *'
  push:
    paths: ['dockerfiles/r-gdalraster.Dockerfile', '.github/workflows/docker-r-gdalraster.yml', 'scripts/install-r-gdalraster.sh']
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (r-gdalraster) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/r-gdalraster.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:r-gdalraster
      - name: Publish (r-gdalraster)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:r-gdalraster
