
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 4 */2 * *'
  push:
    paths: ['dockerfiles/gdal-deps-jupylab.Dockerfile', '.github/workflows/docker-gdal-deps-jupylab.yml', 'scripts/install-jupylab.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (gdal-deps-jupylab) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/gdal-deps-jupylab.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:gdal-deps-jupylab
      - name: Publish (gdal-deps+jupylab)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:gdal-deps-jupylab
